name: Build and publish flutter-builder

on: [release]

jobs:
  build_and_push_flutter_builder:
    name: Build and publish flutter-builder
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          description: An image to build flutter apps APKs (image's tag is indexed on flutter's version supported)
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/cashmanager-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/cashmanager-api:${{ github.ref_name }}
        